# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-10 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('ra', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120)),
                ('email', models.CharField(blank=True, max_length=80, null=True)),
                ('celular', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'db_table': 'aluno',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('sigla', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'curso',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='aluno',
            name='sigla_curso',
            field=models.ForeignKey(db_column='sigla_curso', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Curso'),
        ),
    ]
