# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-10 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeCurricular',
            fields=[
                ('sigla_curso', models.ForeignKey(db_column='sigla_curso', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.Curso')),
                ('ano', models.SmallIntegerField()),
                ('semestre', models.CharField(max_length=1)),
            ],
            options={
                'managed': False,
                'db_table': 'gradecurricular',
            },
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='sigla_curso',
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='Aluno',
        ),
    ]
